[package]
name = "rpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.10.0"
gnupg-rs = "0.1.0"
git2 = "0.18.2"
clap = { version = "4.5.2", features = ["derive"] }
home = "0.5.9"
